/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DpListenDTO { 
    filelocation?: string;
    filelocationt2?: string;
    insertts?: Date;
    rowcount?: number;
    runid?: number;
    status?: string;
    taskid?: number;
    dpid?: number;
    taskname?: string;
    updatets?: Date;
}
