/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TaskMainDTO { 
    createdby?: number;
    dbtypesys1?: string;
    dbtypesys2?: string;
    endtsClobsys1?: string;
    endtsClobsys2?: string;
    endtsOnlinesys1?: string;
    endtsOnlinesys2?: string;
    endtssys1?: string;
    endtssys2?: string;
    filelocation?: string;
    filelocation2?: string;
    insertts?: Date;
    jdbcurlsys1?: string;
    jdbcurlsys2?: string;
    passwordsys1?: string;
    passwordsys2?: string;
    rowcount?: number;
    shared?: string;
    starttsClobsys1?: string;
    starttsClobsys2?: string;
    starttsOnlinesys1?: string;
    starttsOnlinesys2?: string;
    starttssys1?: string;
    starttssys2?: string;
    status?: string;
    sys1type?: string;
    sys2type?: string;
    tablenameClobsys1?: string;
    tablenameClobsys2?: string;
    tablenameOnlinesys1?: string;
    tablenameOnlinesys2?: string;
    tablenamesys1?: string;
    tablenamesys2?: string;
    taskid?: number;
    taskname?: string;
    updatets?: Date;
    usernamesys1?: string;
    usernamesys2?: string;
}
