/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable } from 'rxjs';

import { RolemasterDTO } from '../model/rolemasterDTO';
import { UserDTO } from '../model/userDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class UserControllerService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * deleterolemaster
     * 
     * @param rolemasterid rolemasterid
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleterolemasterUsingDELETE(rolemasterid: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleterolemasterUsingDELETE(rolemasterid: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleterolemasterUsingDELETE(rolemasterid: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleterolemasterUsingDELETE(rolemasterid: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (rolemasterid === null || rolemasterid === undefined) {
            throw new Error('Required parameter rolemasterid was null or undefined when calling deleterolemasterUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/rolemaster/${encodeURIComponent(String(rolemasterid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteuser
     * 
     * @param userid userid
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteuserUsingDELETE(userid: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteuserUsingDELETE(userid: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteuserUsingDELETE(userid: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteuserUsingDELETE(userid: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (userid === null || userid === undefined) {
            throw new Error('Required parameter userid was null or undefined when calling deleteuserUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/user/${encodeURIComponent(String(userid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAllUsers
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllUsersUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<RolemasterDTO>>;
    public getAllUsersUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<RolemasterDTO>>>;
    public getAllUsersUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<RolemasterDTO>>>;
    public getAllUsersUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<RolemasterDTO>>(`${this.basePath}/rolemaster`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getUsers
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getUsersUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<UserDTO>>;
    public getUsersUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<UserDTO>>>;
    public getUsersUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<UserDTO>>>;
    public getUsersUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<UserDTO>>(`${this.basePath}/user`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getrolemasters
     * 
     * @param rolemasterid rolemasterid
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getrolemastersUsingGET(rolemasterid: number, observe?: 'body', reportProgress?: boolean): Observable<RolemasterDTO>;
    public getrolemastersUsingGET(rolemasterid: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RolemasterDTO>>;
    public getrolemastersUsingGET(rolemasterid: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RolemasterDTO>>;
    public getrolemastersUsingGET(rolemasterid: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (rolemasterid === null || rolemasterid === undefined) {
            throw new Error('Required parameter rolemasterid was null or undefined when calling getrolemastersUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<RolemasterDTO>(`${this.basePath}/rolemaster/${encodeURIComponent(String(rolemasterid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getusers
     * 
     * @param userid userid
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getusersUsingGET(userid: number, observe?: 'body', reportProgress?: boolean): Observable<UserDTO>;
    public getusersUsingGET(userid: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserDTO>>;
    public getusersUsingGET(userid: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserDTO>>;
    public getusersUsingGET(userid: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (userid === null || userid === undefined) {
            throw new Error('Required parameter userid was null or undefined when calling getusersUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<UserDTO>(`${this.basePath}/user/${encodeURIComponent(String(userid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * saverolemaster
     * 
     * @param rolemasterDTO rolemasterDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public saverolemasterUsingPOST(rolemasterDTO: RolemasterDTO, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public saverolemasterUsingPOST(rolemasterDTO: RolemasterDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public saverolemasterUsingPOST(rolemasterDTO: RolemasterDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public saverolemasterUsingPOST(rolemasterDTO: RolemasterDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (rolemasterDTO === null || rolemasterDTO === undefined) {
            throw new Error('Required parameter rolemasterDTO was null or undefined when calling saverolemasterUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<number>(`${this.basePath}/rolemaster`,
            rolemasterDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * saveuser
     * 
     * @param userDTO userDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public saveuserUsingPOST(userDTO: UserDTO, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public saveuserUsingPOST(userDTO: UserDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public saveuserUsingPOST(userDTO: UserDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public saveuserUsingPOST(userDTO: UserDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (userDTO === null || userDTO === undefined) {
            throw new Error('Required parameter userDTO was null or undefined when calling saveuserUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<number>(`${this.basePath}/user`,
            userDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update
     * 
     * @param rolemasterDTO rolemasterDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateUsingPUT3(rolemasterDTO: RolemasterDTO, observe?: 'body', reportProgress?: boolean): Observable<RolemasterDTO>;
    public updateUsingPUT3(rolemasterDTO: RolemasterDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RolemasterDTO>>;
    public updateUsingPUT3(rolemasterDTO: RolemasterDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RolemasterDTO>>;
    public updateUsingPUT3(rolemasterDTO: RolemasterDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (rolemasterDTO === null || rolemasterDTO === undefined) {
            throw new Error('Required parameter rolemasterDTO was null or undefined when calling updateUsingPUT3.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<RolemasterDTO>(`${this.basePath}/rolemaster`,
            rolemasterDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update
     * 
     * @param userDTO userDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateUsingPUT4(userDTO: UserDTO, observe?: 'body', reportProgress?: boolean): Observable<UserDTO>;
    public updateUsingPUT4(userDTO: UserDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserDTO>>;
    public updateUsingPUT4(userDTO: UserDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserDTO>>;
    public updateUsingPUT4(userDTO: UserDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (userDTO === null || userDTO === undefined) {
            throw new Error('Required parameter userDTO was null or undefined when calling updateUsingPUT4.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<UserDTO>(`${this.basePath}/user`,
            userDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
